//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartFactory.WinApp.ServiceRef {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceRef.IMachineService")]
    public interface IMachineService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMachineService/SetMachinePerformance", ReplyAction="http://tempuri.org/IMachineService/SetMachinePerformanceResponse")]
        bool SetMachinePerformance(int ruleId, double newThreshold, string machineName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMachineService/SetMachinePerformance", ReplyAction="http://tempuri.org/IMachineService/SetMachinePerformanceResponse")]
        System.Threading.Tasks.Task<bool> SetMachinePerformanceAsync(int ruleId, double newThreshold, string machineName);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IMachineServiceChannel : SmartFactory.WinApp.ServiceRef.IMachineService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MachineServiceClient : System.ServiceModel.ClientBase<SmartFactory.WinApp.ServiceRef.IMachineService>, SmartFactory.WinApp.ServiceRef.IMachineService {
        
        public MachineServiceClient() {
        }
        
        public MachineServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public MachineServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MachineServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MachineServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool SetMachinePerformance(int ruleId, double newThreshold, string machineName) {
            return base.Channel.SetMachinePerformance(ruleId, newThreshold, machineName);
        }
        
        public System.Threading.Tasks.Task<bool> SetMachinePerformanceAsync(int ruleId, double newThreshold, string machineName) {
            return base.Channel.SetMachinePerformanceAsync(ruleId, newThreshold, machineName);
        }
    }
}
